module Git

  module Git_Cert_T
    GIT_CERT_NONE = 0
    GIT_CERT_X509 = 1
    GIT_CERT_HOSTKEY_LIBSSH2 = 2
    GIT_CERT_STRARRAY = 3
  end

  module Git_Remote_Completion_Type
    GIT_REMOTE_COMPLETION_DOWNLOAD = 0
    GIT_REMOTE_COMPLETION_INDEXING = 1
    GIT_REMOTE_COMPLETION_ERROR = 2
  end

  module Git_Attr_T
    GIT_ATTR_UNSPECIFIED_T = 0
    GIT_ATTR_TRUE_T = 1
    GIT_ATTR_FALSE_T = 2
    GIT_ATTR_VALUE_T = 3
  end

  module Git_Blame_Flag_T
    GIT_BLAME_NORMAL = 0
    GIT_BLAME_TRACK_COPIES_SAME_FILE = 1
    GIT_BLAME_TRACK_COPIES_SAME_COMMIT_MOVES = 2
    GIT_BLAME_TRACK_COPIES_SAME_COMMIT_COPIES = 4
    GIT_BLAME_TRACK_COPIES_ANY_COMMIT_COPIES = 8
    GIT_BLAME_FIRST_PARENT = 16
  end

  module Git_Branch_T
    GIT_BRANCH_LOCAL = 1
    GIT_BRANCH_REMOTE = 2
    GIT_BRANCH_ALL = 3
  end

  module Git_Cert_Ssh_T
    GIT_CERT_SSH_MD5 = 1
    GIT_CERT_SSH_SHA1 = 2
  end

  module Git_Checkout_Notify_T
    GIT_CHECKOUT_NOTIFY_NONE = 0
    GIT_CHECKOUT_NOTIFY_CONFLICT = 1
    GIT_CHECKOUT_NOTIFY_DIRTY = 2
    GIT_CHECKOUT_NOTIFY_UPDATED = 4
    GIT_CHECKOUT_NOTIFY_UNTRACKED = 8
    GIT_CHECKOUT_NOTIFY_IGNORED = 16
    GIT_CHECKOUT_NOTIFY_ALL = 65535
  end

  module Git_Checkout_Strategy_T
    GIT_CHECKOUT_NONE = 0
    GIT_CHECKOUT_SAFE = 1
    GIT_CHECKOUT_FORCE = 2
    GIT_CHECKOUT_RECREATE_MISSING = 4
    GIT_CHECKOUT_ALLOW_CONFLICTS = 16
    GIT_CHECKOUT_REMOVE_UNTRACKED = 32
    GIT_CHECKOUT_REMOVE_IGNORED = 64
    GIT_CHECKOUT_UPDATE_ONLY = 128
    GIT_CHECKOUT_DONT_UPDATE_INDEX = 256
    GIT_CHECKOUT_NO_REFRESH = 512
    GIT_CHECKOUT_SKIP_UNMERGED = 1024
    GIT_CHECKOUT_USE_OURS = 2048
    GIT_CHECKOUT_USE_THEIRS = 4096
    GIT_CHECKOUT_DISABLE_PATHSPEC_MATCH = 8192
    GIT_CHECKOUT_SKIP_LOCKED_DIRECTORIES = 262144
    GIT_CHECKOUT_DONT_OVERWRITE_IGNORED = 524288
    GIT_CHECKOUT_CONFLICT_STYLE_MERGE = 1048576
    GIT_CHECKOUT_CONFLICT_STYLE_DIFF3 = 2097152
    GIT_CHECKOUT_DONT_REMOVE_EXISTING = 4194304
    GIT_CHECKOUT_DONT_WRITE_INDEX = 8388608
    GIT_CHECKOUT_UPDATE_SUBMODULES = 65536
    GIT_CHECKOUT_UPDATE_SUBMODULES_IF_CHANGED = 131072
  end

  module Git_Clone_Local_T
    GIT_CLONE_LOCAL_AUTO = 0
    GIT_CLONE_LOCAL = 1
    GIT_CLONE_NO_LOCAL = 2
    GIT_CLONE_LOCAL_NO_LINKS = 3
  end

  module Git_Config_Level_T
    GIT_CONFIG_LEVEL_PROGRAMDATA = 1
    GIT_CONFIG_LEVEL_SYSTEM = 2
    GIT_CONFIG_LEVEL_XDG = 3
    GIT_CONFIG_LEVEL_GLOBAL = 4
    GIT_CONFIG_LEVEL_LOCAL = 5
    GIT_CONFIG_LEVEL_APP = 6
    GIT_CONFIG_HIGHEST_LEVEL = -1
  end

  module Git_Credtype_T
    GIT_CREDTYPE_USERPASS_PLAINTEXT = 1
    GIT_CREDTYPE_SSH_KEY = 2
    GIT_CREDTYPE_SSH_CUSTOM = 4
    GIT_CREDTYPE_DEFAULT = 8
    GIT_CREDTYPE_SSH_INTERACTIVE = 16
    GIT_CREDTYPE_USERNAME = 32
    GIT_CREDTYPE_SSH_MEMORY = 64
  end

  module Git_Cvar_T
    GIT_CVAR_FALSE = 0
    GIT_CVAR_TRUE = 1
    GIT_CVAR_INT32 = 2
    GIT_CVAR_STRING = 3
  end

  module Git_Delta_T
    GIT_DELTA_UNMODIFIED = 0
    GIT_DELTA_ADDED = 1
    GIT_DELTA_DELETED = 2
    GIT_DELTA_MODIFIED = 3
    GIT_DELTA_RENAMED = 4
    GIT_DELTA_COPIED = 5
    GIT_DELTA_IGNORED = 6
    GIT_DELTA_UNTRACKED = 7
    GIT_DELTA_TYPECHANGE = 8
    GIT_DELTA_UNREADABLE = 9
    GIT_DELTA_CONFLICTED = 10
  end

  module Git_Describe_Strategy_T
    GIT_DESCRIBE_DEFAULT = 0
    GIT_DESCRIBE_TAGS = 1
    GIT_DESCRIBE_ALL = 2
  end

  module Git_Diff_Binary_T
    GIT_DIFF_BINARY_NONE = 0
    GIT_DIFF_BINARY_LITERAL = 1
    GIT_DIFF_BINARY_DELTA = 2
  end

  module Git_Diff_Find_T
    GIT_DIFF_FIND_BY_CONFIG = 0
    GIT_DIFF_FIND_RENAMES = 1
    GIT_DIFF_FIND_RENAMES_FROM_REWRITES = 2
    GIT_DIFF_FIND_COPIES = 4
    GIT_DIFF_FIND_COPIES_FROM_UNMODIFIED = 8
    GIT_DIFF_FIND_REWRITES = 16
    GIT_DIFF_BREAK_REWRITES = 32
    GIT_DIFF_FIND_AND_BREAK_REWRITES = 48
    GIT_DIFF_FIND_FOR_UNTRACKED = 64
    GIT_DIFF_FIND_ALL = 255
    GIT_DIFF_FIND_IGNORE_LEADING_WHITESPACE = 0
    GIT_DIFF_FIND_IGNORE_WHITESPACE = 4096
    GIT_DIFF_FIND_DONT_IGNORE_WHITESPACE = 8192
    GIT_DIFF_FIND_EXACT_MATCH_ONLY = 16384
    GIT_DIFF_BREAK_REWRITES_FOR_RENAMES_ONLY = 32768
    GIT_DIFF_FIND_REMOVE_UNMODIFIED = 65536
  end

  module Git_Diff_Flag_T
    GIT_DIFF_FLAG_BINARY = 1
    GIT_DIFF_FLAG_NOT_BINARY = 2
    GIT_DIFF_FLAG_VALID_ID = 4
    GIT_DIFF_FLAG_EXISTS = 8
  end

  module Git_Diff_Format_Email_Flags_T
    GIT_DIFF_FORMAT_EMAIL_NONE = 0
    GIT_DIFF_FORMAT_EMAIL_EXCLUDE_SUBJECT_PATCH_MARKER = 1
  end

  module Git_Diff_Format_T
    GIT_DIFF_FORMAT_PATCH = 1
    GIT_DIFF_FORMAT_PATCH_HEADER = 2
    GIT_DIFF_FORMAT_RAW = 3
    GIT_DIFF_FORMAT_NAME_ONLY = 4
    GIT_DIFF_FORMAT_NAME_STATUS = 5
  end

  module Git_Diff_Line_T
    GIT_DIFF_LINE_CONTEXT = 32
    GIT_DIFF_LINE_ADDITION = 43
    GIT_DIFF_LINE_DELETION = 45
    GIT_DIFF_LINE_CONTEXT_EOFNL = 61
    GIT_DIFF_LINE_ADD_EOFNL = 62
    GIT_DIFF_LINE_DEL_EOFNL = 60
    GIT_DIFF_LINE_FILE_HDR = 70
    GIT_DIFF_LINE_HUNK_HDR = 72
    GIT_DIFF_LINE_BINARY = 66
  end

  module Git_Diff_Option_T
    GIT_DIFF_NORMAL = 0
    GIT_DIFF_REVERSE = 1
    GIT_DIFF_INCLUDE_IGNORED = 2
    GIT_DIFF_RECURSE_IGNORED_DIRS = 4
    GIT_DIFF_INCLUDE_UNTRACKED = 8
    GIT_DIFF_RECURSE_UNTRACKED_DIRS = 16
    GIT_DIFF_INCLUDE_UNMODIFIED = 32
    GIT_DIFF_INCLUDE_TYPECHANGE = 64
    GIT_DIFF_INCLUDE_TYPECHANGE_TREES = 128
    GIT_DIFF_IGNORE_FILEMODE = 256
    GIT_DIFF_IGNORE_SUBMODULES = 512
    GIT_DIFF_IGNORE_CASE = 1024
    GIT_DIFF_INCLUDE_CASECHANGE = 2048
    GIT_DIFF_DISABLE_PATHSPEC_MATCH = 4096
    GIT_DIFF_SKIP_BINARY_CHECK = 8192
    GIT_DIFF_ENABLE_FAST_UNTRACKED_DIRS = 16384
    GIT_DIFF_UPDATE_INDEX = 32768
    GIT_DIFF_INCLUDE_UNREADABLE = 65536
    GIT_DIFF_INCLUDE_UNREADABLE_AS_UNTRACKED = 131072
    GIT_DIFF_FORCE_TEXT = 1048576
    GIT_DIFF_FORCE_BINARY = 2097152
    GIT_DIFF_IGNORE_WHITESPACE = 4194304
    GIT_DIFF_IGNORE_WHITESPACE_CHANGE = 8388608
    GIT_DIFF_IGNORE_WHITESPACE_EOL = 16777216
    GIT_DIFF_SHOW_UNTRACKED_CONTENT = 33554432
    GIT_DIFF_SHOW_UNMODIFIED = 67108864
    GIT_DIFF_PATIENCE = 268435456
    GIT_DIFF_MINIMAL = 536870912
    GIT_DIFF_SHOW_BINARY = 1073741824
  end

  module Git_Diff_Stats_Format_T
    GIT_DIFF_STATS_NONE = 0
    GIT_DIFF_STATS_FULL = 1
    GIT_DIFF_STATS_SHORT = 2
    GIT_DIFF_STATS_NUMBER = 4
    GIT_DIFF_STATS_INCLUDE_SUMMARY = 8
  end

  module Git_Direction
    GIT_DIRECTION_FETCH = 0
    GIT_DIRECTION_PUSH = 1
  end

  module Git_Error_Code
    GIT_OK = 0
    GIT_ERROR = -1
    GIT_ENOTFOUND = -3
    GIT_EEXISTS = -4
    GIT_EAMBIGUOUS = -5
    GIT_EBUFS = -6
    GIT_EUSER = -7
    GIT_EBAREREPO = -8
    GIT_EUNBORNBRANCH = -9
    GIT_EUNMERGED = -10
    GIT_ENONFASTFORWARD = -11
    GIT_EINVALIDSPEC = -12
    GIT_ECONFLICT = -13
    GIT_ELOCKED = -14
    GIT_EMODIFIED = -15
    GIT_EAUTH = -16
    GIT_ECERTIFICATE = -17
    GIT_EAPPLIED = -18
    GIT_EPEEL = -19
    GIT_EEOF = -20
    GIT_EINVALID = -21
    GIT_EUNCOMMITTED = -22
    GIT_EDIRECTORY = -23
    GIT_EMERGECONFLICT = -24
    GIT_PASSTHROUGH = -30
    GIT_ITEROVER = -31
  end

  module Git_Error_T
    GITERR_NONE = 0
    GITERR_NOMEMORY = 1
    GITERR_OS = 2
    GITERR_INVALID = 3
    GITERR_REFERENCE = 4
    GITERR_ZLIB = 5
    GITERR_REPOSITORY = 6
    GITERR_CONFIG = 7
    GITERR_REGEX = 8
    GITERR_ODB = 9
    GITERR_INDEX = 10
    GITERR_OBJECT = 11
    GITERR_NET = 12
    GITERR_TAG = 13
    GITERR_TREE = 14
    GITERR_INDEXER = 15
    GITERR_SSL = 16
    GITERR_SUBMODULE = 17
    GITERR_THREAD = 18
    GITERR_STASH = 19
    GITERR_CHECKOUT = 20
    GITERR_FETCHHEAD = 21
    GITERR_MERGE = 22
    GITERR_SSH = 23
    GITERR_FILTER = 24
    GITERR_REVERT = 25
    GITERR_CALLBACK = 26
    GITERR_CHERRYPICK = 27
    GITERR_DESCRIBE = 28
    GITERR_REBASE = 29
    GITERR_FILESYSTEM = 30
  end

  module Git_Feature_T
    GIT_FEATURE_THREADS = 1
    GIT_FEATURE_HTTPS = 2
    GIT_FEATURE_SSH = 4
    GIT_FEATURE_NSEC = 8
  end

  module Git_Fetch_Prune_T
    GIT_FETCH_PRUNE_UNSPECIFIED = 0
    GIT_FETCH_PRUNE = 1
    GIT_FETCH_NO_PRUNE = 2
  end

  module Git_Filemode_T
    GIT_FILEMODE_UNREADABLE = 0
    GIT_FILEMODE_TREE = 16384
    GIT_FILEMODE_BLOB = 33188
    GIT_FILEMODE_BLOB_EXECUTABLE = 33261
    GIT_FILEMODE_LINK = 40960
    GIT_FILEMODE_COMMIT = 57344
  end

  module Git_Filter_Flag_T
    GIT_FILTER_DEFAULT = 0
    GIT_FILTER_ALLOW_UNSAFE = 1
  end

  module Git_Filter_Mode_T
    GIT_FILTER_TO_WORKTREE = 0
    GIT_FILTER_SMUDGE = 0
    GIT_FILTER_TO_ODB = 1
    GIT_FILTER_CLEAN = 1
  end

  module Git_Idxentry_Extended_Flag_T
    GIT_IDXENTRY_INTENT_TO_ADD = 8192
    GIT_IDXENTRY_SKIP_WORKTREE = 16384
    GIT_IDXENTRY_EXTENDED2 = 32768
    GIT_IDXENTRY_EXTENDED_FLAGS = 24576
    GIT_IDXENTRY_UPDATE = 1
    GIT_IDXENTRY_REMOVE = 2
    GIT_IDXENTRY_UPTODATE = 4
    GIT_IDXENTRY_ADDED = 8
    GIT_IDXENTRY_HASHED = 16
    GIT_IDXENTRY_UNHASHED = 32
    GIT_IDXENTRY_WT_REMOVE = 64
    GIT_IDXENTRY_CONFLICTED = 128
    GIT_IDXENTRY_UNPACKED = 256
    GIT_IDXENTRY_NEW_SKIP_WORKTREE = 512
  end

  module Git_Index_Add_Option_T
    GIT_INDEX_ADD_DEFAULT = 0
    GIT_INDEX_ADD_FORCE = 1
    GIT_INDEX_ADD_DISABLE_PATHSPEC_MATCH = 2
    GIT_INDEX_ADD_CHECK_PATHSPEC = 4
  end

  module Git_Index_Stage_T
    GIT_INDEX_STAGE_ANY = -1
    GIT_INDEX_STAGE_NORMAL = 0
    GIT_INDEX_STAGE_ANCESTOR = 1
    GIT_INDEX_STAGE_OURS = 2
    GIT_INDEX_STAGE_THEIRS = 3
  end

  module Git_Indexcap_T
    GIT_INDEXCAP_IGNORE_CASE = 1
    GIT_INDEXCAP_NO_FILEMODE = 2
    GIT_INDEXCAP_NO_SYMLINKS = 4
    GIT_INDEXCAP_FROM_OWNER = -1
  end

  module Git_Indxentry_Flag_T
    GIT_IDXENTRY_EXTENDED = 16384
    GIT_IDXENTRY_VALID = 32768
  end

  module Git_Libgit2_Opt_T
    GIT_OPT_GET_MWINDOW_SIZE = 0
    GIT_OPT_SET_MWINDOW_SIZE = 1
    GIT_OPT_GET_MWINDOW_MAPPED_LIMIT = 2
    GIT_OPT_SET_MWINDOW_MAPPED_LIMIT = 3
    GIT_OPT_GET_SEARCH_PATH = 4
    GIT_OPT_SET_SEARCH_PATH = 5
    GIT_OPT_SET_CACHE_OBJECT_LIMIT = 6
    GIT_OPT_SET_CACHE_MAX_SIZE = 7
    GIT_OPT_ENABLE_CACHING = 8
    GIT_OPT_GET_CACHED_MEMORY = 9
    GIT_OPT_GET_TEMPLATE_PATH = 10
    GIT_OPT_SET_TEMPLATE_PATH = 11
    GIT_OPT_SET_SSL_CERT_LOCATIONS = 12
    GIT_OPT_SET_USER_AGENT = 13
  end

  module Git_Merge_Analysis_T
    GIT_MERGE_ANALYSIS_NONE = 0
    GIT_MERGE_ANALYSIS_NORMAL = 1
    GIT_MERGE_ANALYSIS_UP_TO_DATE = 2
    GIT_MERGE_ANALYSIS_FASTFORWARD = 4
    GIT_MERGE_ANALYSIS_UNBORN = 8
  end

  module Git_Merge_File_Favor_T
    GIT_MERGE_FILE_FAVOR_NORMAL = 0
    GIT_MERGE_FILE_FAVOR_OURS = 1
    GIT_MERGE_FILE_FAVOR_THEIRS = 2
    GIT_MERGE_FILE_FAVOR_UNION = 3
  end

  module Git_Merge_File_Flag_T
    GIT_MERGE_FILE_DEFAULT = 0
    GIT_MERGE_FILE_STYLE_MERGE = 1
    GIT_MERGE_FILE_STYLE_DIFF3 = 2
    GIT_MERGE_FILE_SIMPLIFY_ALNUM = 4
    GIT_MERGE_FILE_IGNORE_WHITESPACE = 8
    GIT_MERGE_FILE_IGNORE_WHITESPACE_CHANGE = 16
    GIT_MERGE_FILE_IGNORE_WHITESPACE_EOL = 32
    GIT_MERGE_FILE_DIFF_PATIENCE = 64
    GIT_MERGE_FILE_DIFF_MINIMAL = 128
  end

  module Git_Merge_Flag_T
    GIT_MERGE_FIND_RENAMES = 1
    GIT_MERGE_FAIL_ON_CONFLICT = 2
    GIT_MERGE_SKIP_REUC = 4
    GIT_MERGE_NO_RECURSIVE = 8
  end

  module Git_Merge_Preference_T
    GIT_MERGE_PREFERENCE_NONE = 0
    GIT_MERGE_PREFERENCE_NO_FASTFORWARD = 1
    GIT_MERGE_PREFERENCE_FASTFORWARD_ONLY = 2
  end

  module Git_Odb_Stream_T
    GIT_STREAM_RDONLY = 2
    GIT_STREAM_WRONLY = 4
    GIT_STREAM_RW = 6
  end

  module Git_Otype
    GIT_OBJ_ANY = -2
    GIT_OBJ_BAD = -1
    GIT_OBJ__EXT1 = 0
    GIT_OBJ_COMMIT = 1
    GIT_OBJ_TREE = 2
    GIT_OBJ_BLOB = 3
    GIT_OBJ_TAG = 4
    GIT_OBJ__EXT2 = 5
    GIT_OBJ_OFS_DELTA = 6
    GIT_OBJ_REF_DELTA = 7
  end

  module Git_Packbuilder_Stage_T
    GIT_PACKBUILDER_ADDING_OBJECTS = 0
    GIT_PACKBUILDER_DELTAFICATION = 1
  end

  module Git_Pathspec_Flag_T
    GIT_PATHSPEC_DEFAULT = 0
    GIT_PATHSPEC_IGNORE_CASE = 1
    GIT_PATHSPEC_USE_CASE = 2
    GIT_PATHSPEC_NO_GLOB = 4
    GIT_PATHSPEC_NO_MATCH_ERROR = 8
    GIT_PATHSPEC_FIND_FAILURES = 16
    GIT_PATHSPEC_FAILURES_ONLY = 32
  end

  module Git_Rebase_Operation_T
    GIT_REBASE_OPERATION_PICK = 0
    GIT_REBASE_OPERATION_REWORD = 1
    GIT_REBASE_OPERATION_EDIT = 2
    GIT_REBASE_OPERATION_SQUASH = 3
    GIT_REBASE_OPERATION_FIXUP = 4
    GIT_REBASE_OPERATION_EXEC = 5
  end

  module Git_Ref_T
    GIT_REF_INVALID = 0
    GIT_REF_OID = 1
    GIT_REF_SYMBOLIC = 2
    GIT_REF_LISTALL = 3
  end

  module Git_Reference_Normalize_T
    GIT_REF_FORMAT_NORMAL = 0
    GIT_REF_FORMAT_ALLOW_ONELEVEL = 1
    GIT_REF_FORMAT_REFSPEC_PATTERN = 2
    GIT_REF_FORMAT_REFSPEC_SHORTHAND = 4
  end

  module Git_Remote_Autotag_Option_T
    GIT_REMOTE_DOWNLOAD_TAGS_UNSPECIFIED = 0
    GIT_REMOTE_DOWNLOAD_TAGS_AUTO = 1
    GIT_REMOTE_DOWNLOAD_TAGS_NONE = 2
    GIT_REMOTE_DOWNLOAD_TAGS_ALL = 3
  end

  module Git_Repository_Init_Flag_T
    GIT_REPOSITORY_INIT_BARE = 1
    GIT_REPOSITORY_INIT_NO_REINIT = 2
    GIT_REPOSITORY_INIT_NO_DOTGIT_DIR = 4
    GIT_REPOSITORY_INIT_MKDIR = 8
    GIT_REPOSITORY_INIT_MKPATH = 16
    GIT_REPOSITORY_INIT_EXTERNAL_TEMPLATE = 32
    GIT_REPOSITORY_INIT_RELATIVE_GITLINK = 64
  end

  module Git_Repository_Init_Mode_T
    GIT_REPOSITORY_INIT_SHARED_UMASK = 0
    GIT_REPOSITORY_INIT_SHARED_GROUP = 1533
    GIT_REPOSITORY_INIT_SHARED_ALL = 1535
  end

  module Git_Repository_Open_Flag_T
    GIT_REPOSITORY_OPEN_NO_SEARCH = 1
    GIT_REPOSITORY_OPEN_CROSS_FS = 2
    GIT_REPOSITORY_OPEN_BARE = 4
  end

  module Git_Repository_State_T
    GIT_REPOSITORY_STATE_NONE = 0
    GIT_REPOSITORY_STATE_MERGE = 1
    GIT_REPOSITORY_STATE_REVERT = 2
    GIT_REPOSITORY_STATE_REVERT_SEQUENCE = 3
    GIT_REPOSITORY_STATE_CHERRYPICK = 4
    GIT_REPOSITORY_STATE_CHERRYPICK_SEQUENCE = 5
    GIT_REPOSITORY_STATE_BISECT = 6
    GIT_REPOSITORY_STATE_REBASE = 7
    GIT_REPOSITORY_STATE_REBASE_INTERACTIVE = 8
    GIT_REPOSITORY_STATE_REBASE_MERGE = 9
    GIT_REPOSITORY_STATE_APPLY_MAILBOX = 10
    GIT_REPOSITORY_STATE_APPLY_MAILBOX_OR_REBASE = 11
  end

  module Git_Reset_T
    GIT_RESET_SOFT = 1
    GIT_RESET_MIXED = 2
    GIT_RESET_HARD = 3
  end

  module Git_Revparse_Mode_T
    GIT_REVPARSE_SINGLE = 1
    GIT_REVPARSE_RANGE = 2
    GIT_REVPARSE_MERGE_BASE = 4
  end

  module Git_Sort_T
    GIT_SORT_NONE = 0
    GIT_SORT_TOPOLOGICAL = 1
    GIT_SORT_TIME = 2
    GIT_SORT_REVERSE = 4
  end

  module Git_Stash_Apply_Flags
    GIT_STASH_APPLY_DEFAULT = 0
    GIT_STASH_APPLY_REINSTATE_INDEX = 1
  end

  module Git_Stash_Apply_Progress_T
    GIT_STASH_APPLY_PROGRESS_NONE = 0
    GIT_STASH_APPLY_PROGRESS_LOADING_STASH = 1
    GIT_STASH_APPLY_PROGRESS_ANALYZE_INDEX = 2
    GIT_STASH_APPLY_PROGRESS_ANALYZE_MODIFIED = 3
    GIT_STASH_APPLY_PROGRESS_ANALYZE_UNTRACKED = 4
    GIT_STASH_APPLY_PROGRESS_CHECKOUT_UNTRACKED = 5
    GIT_STASH_APPLY_PROGRESS_CHECKOUT_MODIFIED = 6
    GIT_STASH_APPLY_PROGRESS_DONE = 7
  end

  module Git_Stash_Flags
    GIT_STASH_DEFAULT = 0
    GIT_STASH_KEEP_INDEX = 1
    GIT_STASH_INCLUDE_UNTRACKED = 2
    GIT_STASH_INCLUDE_IGNORED = 4
  end

  module Git_Status_Opt_T
    GIT_STATUS_OPT_INCLUDE_UNTRACKED = 1
    GIT_STATUS_OPT_INCLUDE_IGNORED = 2
    GIT_STATUS_OPT_INCLUDE_UNMODIFIED = 4
    GIT_STATUS_OPT_EXCLUDE_SUBMODULES = 8
    GIT_STATUS_OPT_RECURSE_UNTRACKED_DIRS = 16
    GIT_STATUS_OPT_DISABLE_PATHSPEC_MATCH = 32
    GIT_STATUS_OPT_RECURSE_IGNORED_DIRS = 64
    GIT_STATUS_OPT_RENAMES_HEAD_TO_INDEX = 128
    GIT_STATUS_OPT_RENAMES_INDEX_TO_WORKDIR = 256
    GIT_STATUS_OPT_SORT_CASE_SENSITIVELY = 512
    GIT_STATUS_OPT_SORT_CASE_INSENSITIVELY = 1024
    GIT_STATUS_OPT_RENAMES_FROM_REWRITES = 2048
    GIT_STATUS_OPT_NO_REFRESH = 4096
    GIT_STATUS_OPT_UPDATE_INDEX = 8192
    GIT_STATUS_OPT_INCLUDE_UNREADABLE = 16384
    GIT_STATUS_OPT_INCLUDE_UNREADABLE_AS_UNTRACKED = 32768
  end

  module Git_Status_Show_T
    GIT_STATUS_SHOW_INDEX_AND_WORKDIR = 0
    GIT_STATUS_SHOW_INDEX_ONLY = 1
    GIT_STATUS_SHOW_WORKDIR_ONLY = 2
  end

  module Git_Status_T
    GIT_STATUS_CURRENT = 0
    GIT_STATUS_INDEX_NEW = 1
    GIT_STATUS_INDEX_MODIFIED = 2
    GIT_STATUS_INDEX_DELETED = 4
    GIT_STATUS_INDEX_RENAMED = 8
    GIT_STATUS_INDEX_TYPECHANGE = 16
    GIT_STATUS_WT_NEW = 128
    GIT_STATUS_WT_MODIFIED = 256
    GIT_STATUS_WT_DELETED = 512
    GIT_STATUS_WT_TYPECHANGE = 1024
    GIT_STATUS_WT_RENAMED = 2048
    GIT_STATUS_WT_UNREADABLE = 4096
    GIT_STATUS_IGNORED = 16384
    GIT_STATUS_CONFLICTED = 32768
  end

  module Git_Submodule_Ignore_T
    GIT_SUBMODULE_IGNORE_UNSPECIFIED = -1
    GIT_SUBMODULE_IGNORE_NONE = 1
    GIT_SUBMODULE_IGNORE_UNTRACKED = 2
    GIT_SUBMODULE_IGNORE_DIRTY = 3
    GIT_SUBMODULE_IGNORE_ALL = 4
  end

  module Git_Submodule_Recurse_T
    GIT_SUBMODULE_RECURSE_NO = 0
    GIT_SUBMODULE_RECURSE_YES = 1
    GIT_SUBMODULE_RECURSE_ONDEMAND = 2
  end

  module Git_Submodule_Status_T
    GIT_SUBMODULE_STATUS_IN_HEAD = 1
    GIT_SUBMODULE_STATUS_IN_INDEX = 2
    GIT_SUBMODULE_STATUS_IN_CONFIG = 4
    GIT_SUBMODULE_STATUS_IN_WD = 8
    GIT_SUBMODULE_STATUS_INDEX_ADDED = 16
    GIT_SUBMODULE_STATUS_INDEX_DELETED = 32
    GIT_SUBMODULE_STATUS_INDEX_MODIFIED = 64
    GIT_SUBMODULE_STATUS_WD_UNINITIALIZED = 128
    GIT_SUBMODULE_STATUS_WD_ADDED = 256
    GIT_SUBMODULE_STATUS_WD_DELETED = 512
    GIT_SUBMODULE_STATUS_WD_MODIFIED = 1024
    GIT_SUBMODULE_STATUS_WD_INDEX_MODIFIED = 2048
    GIT_SUBMODULE_STATUS_WD_WD_MODIFIED = 4096
    GIT_SUBMODULE_STATUS_WD_UNTRACKED = 8192
  end

  module Git_Submodule_Update_T
    GIT_SUBMODULE_UPDATE_CHECKOUT = 1
    GIT_SUBMODULE_UPDATE_REBASE = 2
    GIT_SUBMODULE_UPDATE_MERGE = 3
    GIT_SUBMODULE_UPDATE_NONE = 4
    GIT_SUBMODULE_UPDATE_DEFAULT = 0
  end

  module Git_Trace_Level_T
    GIT_TRACE_NONE = 0
    GIT_TRACE_FATAL = 1
    GIT_TRACE_ERROR = 2
    GIT_TRACE_WARN = 3
    GIT_TRACE_INFO = 4
    GIT_TRACE_DEBUG = 5
    GIT_TRACE_TRACE = 6
  end

  module Git_Treewalk_Mode
    GIT_TREEWALK_PRE = 0
    GIT_TREEWALK_POST = 1
  end
end
